actors:
  yunomae:
    image_url: /images/actors/yunomae.png
    name: yunomae
  ayabe:
    image_url: /images/actors/ayabe.png
    name: ayabe
author: yunomae
description: 湯前とカウンセラー綾部による、心理学(Psychology) x 組織(Organization)を語るPodcast
description_long: 湯前とカウンセラー綾部が、アカツキの組織作りと心理学を関連付けながら、今起こっている問題について考えるPodcast
email: yoshihiro.yunomae@aktsk.jp
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: Psychorgy
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title.html
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Psychorgy.fm
url: http://aktsk.jp
